from pathlib import Path
import pytesseract
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

ROOT_DIR = Path(__file__).parent
OUTPUT_DIR = ROOT_DIR / "output"
CACHE_DIR = ROOT_DIR / ".cache"
WEIGHTS_DIR = ROOT_DIR / "weights"
SAMPLE_DIR = ROOT_DIR / "samples"

# YOLO
YOLO_WEIGHTS = WEIGHTS_DIR / "slide_yolov8.pt"
YOLO_CONF_THRESHOLD = 0.25
YOLO_IOU_THRESHOLD = 0.45
YOLO_IMAGE_SIZE = 1280
YOLO_CLASSES = [
    "header", "content_block", "text_zone", "chart_area",
    "table", "image", "icon", "arrow",
]

# Gemini
GEMINI_MODEL = "gemini-2.5-flash"
GEMINI_MAX_TOKENS = 8192
GEMINI_TEMPERATURE = 0.1
GEMINI_ITER_MAX = 2
GEMINI_ITER_STOP_THRESHOLD = 0
GEMINI_RETRY_MAX = 3
GEMINI_RETRY_BACKOFF = [5, 15, 30]

# Merge / Dedup
MERGE_IOU_DUPLICATE_THRESHOLD = 0.5
MERGE_CONTAINMENT_THRESHOLD = 0.85
MERGE_CORRECTION_IOU_THRESHOLD = 0.3

# Semantic types
SEMANTIC_TYPES = [
    "Section", "NestedSection", "TextBlock", "Header",
    "Icon", "DiagramShape", "Arrow", "Table", "Chart", "BackgroundArt",
]

# Phase 2 — Classify
COMPLEXITY_ENTROPY_WEIGHT = 0.4
COMPLEXITY_DETECTION_DENSITY_WEIGHT = 0.3
COMPLEXITY_EDGE_DENSITY_WEIGHT = 0.3
CROP_THRESHOLD = 0.55
ALWAYS_CROP_TYPES = ["BackgroundArt", "Chart", "Icon"]
ALWAYS_RECONSTRUCT_TYPES = ["Header", "TextBlock", "Arrow"]

# Phase 3A — Reconstruct
SHAPE_VERTEX_TOLERANCE = 0.06
SHAPE_STAR_CONCAVITY_RATIO = 0.7
SHAPE_ARROW_ASPECT_RATIO = 4.0
SHAPE_MIN_AREA_PX = 500
FONT_SIZE_MIN_PT = 6
FONT_SIZE_MAX_PT = 72
FONT_SIZE_HEIGHT_RATIO = 0.72
FONT_BOLD_STROKE_RATIO = 0.15
FONT_BOLD_MIN_SIZE_PX = 18
FONT_FAMILY = "Arial"
TEXT_BOX_PADDING_PX = 8
TEXT_COLOR_SAMPLE_RADIUS = 3
OCR_MIN_CONFIDENCE = 60

# Phase 3A — Arrows
ARROW_MIN_LENGTH_PX = 20
ARROW_HOUGH_THRESHOLD = 25
ARROW_HOUGH_MIN_LINE_LENGTH = 15
ARROW_HOUGH_MAX_LINE_GAP = 8
ARROW_LINE_WIDTH_PT = 1.5
ARROW_HEAD_TYPE = "triangle"
ARROW_HEAD_WIDTH = "med"
ARROW_HEAD_LENGTH = "med"

# Phase 3B — Crop
TILE_OUTPUT_DIR = OUTPUT_DIR / "tiles"
FILL_RING_WIDTH_PX = 4
FILL_RING_MIN_SAMPLE_PX = 10
FILL_INK_DARKNESS_THRESHOLD = 80
FILL_FALLBACK_SAMPLE_REGION = 0.1
DARK_BACKGROUND_THRESHOLD = 128
DARK_BG_FILL_BLEND_ALPHA = 0.95

# Phase 4 — Assembly
SLIDE_WIDTH_EMU = 9144000
SLIDE_HEIGHT_EMU = 5143500
SLIDE_WIDTH_PX = 1280
SLIDE_HEIGHT_PX = 720
EMU_PER_PX = SLIDE_WIDTH_EMU / SLIDE_WIDTH_PX
Z_ORDER_BACKGROUND = 0
Z_ORDER_NESTED = 1
Z_ORDER_SHAPES = 2
Z_ORDER_TEXT = 3
GROUP_PADDING_EMU = 0

# Phase 5 — QA
SSIM_PASS_THRESHOLD = 0.85
SSIM_ELEMENT_FLAG_THRESHOLD = 0.70
SSIM_WINDOW_SIZE = 7
SSIM_RENDER_DPI = 150
QA_OUTPUT_DIR = OUTPUT_DIR / "qa"
QA_DIFF_SAVE = True

# Logging
LOG_LEVEL = "INFO"
LOG_DIR = ROOT_DIR / "logs"
LOG_SAVE = True

# Runtime flags
VLM_REFINE_ENABLED = True
DARK_BG_DETECTION_ENABLED = True
DEBUG_SAVE_ANNOTATED_IMAGE = False
USE_CACHE = True